### Collect logs to {{ logs }}

---
- hosts: nodes

  tasks:
  - name: rm -rf logs
    local_action: file path={{ logs }} state=absent
    run_once: true

  - name: fetch logs to {{ logs }}
    fetch:
      src: "{{ pg_logfile }}"
      dest: "{{ logs }}/{{ inventory_hostname }}.log"
      validate_checksum: no # new logs might constantly arrive
      flat: yes
    tags:
      fetch

  - name: find out node id from log
    local_action: shell grep -m 1 -o -P 'SHND \d' logs/{{ inventory_hostname }}.log | sed 's/SHND //'
    register: node_id
    tags:
      node_symlink

  - name: create symlink 'node_id'.log -> 'ip'.log
    local_action: file
      src={{ inventory_hostname }}.log
      dest={{ logs }}/{{ node_id.stdout }}.log
      force=yes
      state=link

  - name: touch logs/united.log
    local_action: copy content="" dest={{ logs }}/united.log
    run_once: true

  - name: unite logs
    local_action: shell cat {{ logs }}/{{ item }}.log >> {{ logs }}/united.log
    with_items: "{{ groups.nodes }}"
    run_once: true

  - name: create symlink to shardlord log
    local_action: file
      src={{ groups['shardlord'][0] }}.log
      dest={{ logs }}/shardlord.log
      force=yes
      state=link
